# Generated by Django 4.1.2 on 2022-10-31 19:22

import apps.articles.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(default='images/defaults/article-default.png', upload_to=apps.articles.models.get_article_upload_path)),
                ('body', tinymce.models.HTMLField()),
                ('number_likes', models.PositiveSmallIntegerField(default=0)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.articles.models.get_assets_upload_path)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.article')),
            ],
        ),
    ]
